export const FETCH_USER="fetch-user";
export const SET_TERM="set-term";
export const SET_TIMER="set-timer";
export const TRACK_SCORE="track-score";
export const TIMER_TICK="timer-tick";
export const TIMER_START="timer-start";
export const TIMER_STOP="timer-stop";
export const VIDEO_TYPE_SELECTED= "video-type-selected";
export const SEARCH_SELECTED="search-selected";
