export const FETCH_USER="fetch-user";
export const GET_TIME="get-time";
export const TRACK_SCORE="track-score";
export const VIDEO_TYPE_SELECTED= "video-type-selected";
export const SEARCH_SELECTED="search-selected";
export const CHECK_ACTIVE="check-active";
export const FETCH_POSTS="check-posts";
export const FETCH_DATA="fetch-data";
export const FETCH_DATA_USER="fetch-data-user";
